uses alles,crt;

var f : File of string;
    st : String;
    anzahl : Word;
begin
 assign(f,'C:\pascal\babylon\planeten.dat');
 rewrite(f);
 anzahl:=0;
 st:='Wolf 359';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Tellar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Andor';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Alpha 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Vega 9';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Deneb 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Marcos 12';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Izar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Rigel 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Cait';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Antos 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Catulla';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Tiburon';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Merak 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Aldebaran';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Mu Leonis 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Argelius 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Daran 5';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Aurelia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Mantilles';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Pallas 14';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Medusa';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Coridan';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Delta';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Sauria';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Yonda';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Theta Kioski 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Bynaus';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Benzar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Phylos 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Antares B 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Argo';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Berengaria 7';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Beta 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Capella 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ceti Alpha 5';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Delos 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Delta Dorado 7';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Dimorus 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Magna Roma';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Eminiar 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Excalbia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Gamma Trianguli';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Iotia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Janus 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Kaferia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Klinzaih';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Lactra 7';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Fotialla';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Triskelion';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Zeon';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Mudd';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Onlines';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Organia 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Regulus';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Talos 4';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Taurus 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Velara 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Zeta Bootis 3';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ferengal';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Tau Lacertae 9';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Tholia 2';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Miracht';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Fesoan';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Kericindal';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Kesir-Tosharra';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Kreta';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ferasa';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Dorafane';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Cendo-Pae';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Simeran';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ardana';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Nelphia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Meriabii';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Visalayan';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Desortriana';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Seyalia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='New Fabrina';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Melkot';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Cyndriel';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Beta Veldonna';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Sigma Regonis';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Pheradon';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Gamma Xertia';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Merari';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Hestalor';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Landru';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Menkar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ornara';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Brekka';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Gideon';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Vendikar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Eminiar';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Vaalel';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Oxmyx';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Shaul';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Kohath-Seredi';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Sesaline';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Ekos';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Arodi';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Clesik';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Beta Tauri';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Neural';
 write(f,st);
 anzahl:=anzahl+1;
 st:='Gornar';
 write(f,st);
 anzahl:=anzahl+1;
 close(f);
 writeln(anzahl);
end.
 st:='';
 write(f,st);
 anzahl:=anzahl+1;
