uses crt,gemischt,utily;
Var name,alter,idol,feind,wohnort:string;
label lala;
begin
 writeln ('K.A.I. -Komische Aprilscherz initialien- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -Kobolt ausehender Idiot- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -Komisches Auáerirdisches Idiotenkind- 1.0');
 readln;
 clrscr;
 Writeln ('K.A.I. -Kaotisch Asozialer Indianer- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -kapute Alien Intelligenz- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -Kai auch indizieren- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -Komiker aus Israel- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -kleines Arschkriechendes Insekt- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -keine Asiatische Inspiration- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -kssen auf Isl„ndisch- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. -Kokain abh„ngiger Itaker- 1.0');
 readln;
 clrscr;
 writeln ('K.A.I. die ultimative Kinderberraschung, ein spiel fr Leute');
 writeln ('die wollen und nicht k”nnen (eben ein K.A.I.)');
 writeln ('Kaufen sie es sich und sie werden ihr Selbstvertrauen nie wieder');
 writeln ('finden, auáer ihr Computer bekommt eine Virus der das Programm');
 writeln ('vernichtet.');
 writeln ('Ich selber werde dieses Spiel nur spielen, wenn A.X.E.L 1.0 nicht');
 writeln ('herauskommen wird.');
 readln;
 writeln ('Testen sie ob sie geeignet sind fr K.A.I.');
 writeln;
 write ('Wie heiáen Sie ? ');
 readln (Name);
 write ('Wie Alt sind sie ? ');
 readln (Alter);
 write ('Gibt es jemanden den sie T”ten wollen ? ');
 readln (Feind);
 write ('Ihr Idol ? ');
 readln (Idol);
 write ('Wo Wohnen sie (Dorf) ? ');
 readln (Wohnort);
 writeln;
 writeln ('So einen doofen Namen wie ',Name,' habe ich noch nie geh”rt');
 writeln ('Du ',Name,' bist ',Alter,' alt, ich habe dich fr sehr viel „lter gehalten');
 writeln ('du wichser.');
 writeln ('Im gegensatzt zu Dir ist ',Feind,' kein holer Arschleckende Holkopf');
 writeln ('Wenn ',Idol,' wissen wrde das du ihn als Idol gew„hlt hast, wrde');
 writeln ('er Selbstmord begehen.');
 readln;
 writeln ('Sie ',Name,' haben, wenn sie nicht ihren Computer zertrmmert haben');
 writeln ('den Test bestanden und k”nnen nun anfangen mit dem Spiel.');
 readln;
 clrscr;
 writeln ('Du befindest dich auf einer sch”nen Wiese, die V”gel zwitschern, die Bienen');
 writeln ('summen durch die Luft, die Blumen blhen.');
 writeln ('Doch dann h”rst du einen Hilferuf.');
 writeln ('Du rennst hin und siehst ein kleines M„dchen, du fragst es warum es schreit');
 writeln ('Sie sagt:"Eine b”se Hexe hat meinen Topf Honig geklaut"');
 writeln ('Du beschlieát dem M„dchen zu helfen und machst dich auf den Weg');
 readln;
 writeln ;
 write ('wohin willst du? ');
 writeln ('N');
 delay (10000);
 clrscr;
 delay (20000);
 writeln ('Du hast dich verlaufen, und als du eine kleine Biene fragst wo es lang geht....');
 delay (20000);
 writeln;
 writeln ('Ich bin es, dein Computer, schalte dieses Programm ab, oder meine Khlung versagt');
 writeln;
 delay (20000);
 writeln ('Die kleine Biene ist so lieb, daá sie sich dir anschlieát ....');
 writeln ;
 delay (20000);
 writeln ('Ich bins wieder dein Computer, ich strtze jetzt ab!!');
 delay (20000);
 Lala:
 goto lala;
end.