{This program was writen by Jensman & WWV}

PROGRAM TWO_STUPID_DOGS;

USES DOGS, CRT;

VAR Readme, Episode, Sprache : String;
    {Episode1}
    dose1, dose2, dose3, dose4, dose5 : String;
    {Episode2}
    Suppe1, Suppe2 : String;
    {Episode3}
    Wahl1, Wahl2, Wahl3 : String;

{Anfang}
label readmeja, Episoden, Deutsch, Sprachen, Ende;
label Episode1, episode1a, episode1b, Episode2, Episode2a, Episode2b;
{Episode1}
label Tueranschau, hundanschau, helianschau, Tueroff, Hundwitz, Helibenutz1, Pferdanschau, Karusellanschau, Pferdbenutz;
label Karusellbenutz, Ortwechsel1, schildanschau, reden, ortwechsel2, anschrei, freundlich, wronganschau, supermarktgehen;
label ratfrag, wrongreden, vogelanschau, wrongbefrei, wronganschrei, wrongschleim;
{Episode2}
label Gelanderanschau, Hundanschau2, Suppeanschau, Suppengehen, Gelandersuppe, Hundreden2, Hundewitz2, Knochenanschau;
label Bodenanschau, Knochennem, Vogelnem, Hundreden3, Hundwitz3, Humpeln, Vogelreden, Knochenwerf, Vogelwerf, Vogelanschau2;
{Episode3}
Label episode3, Bank, Zeitung, Schild;
Label Wald, Baum, Pilzseh, unterhalt, Witz, Baumseh, Pilzess;
label North, Schildles, Tuerguck, Tuerdrueck, Reinguck, Leiterguck, Leiternutz, Kartongguck, Kartongoe, Loch;
Label Dach;



BEGIN
   Highvideo;
   textbackground (0);
   textcolor (cyan);
   ClrScr;
   Writeln ('                       ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹ ');
   Writeln ('                       €2 Stupid Dogs Version 1.0€ ');
   Writeln ('                       ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ ');
   Writeln ('');
   Writeln ('Diese Textadventure beruht auf der Zeichentrickserie TWO STUPID DOGs ! ');
   Writeln ('Es wurde von dem inofficellen TWO STUPID DOGs-Fanclub geschrieben !');
   Writeln;
   warten;
   Write ('Wollen sie die Readmedatei lesen ? ');
   write (' Ja oder nein ');
   Readln (Readme);
   clrscr;
   if (Readme) = ('ja') then goto readmeja;
   if (Readme) = ('nein') then goto Sprachen;
   if (readme) = ('Nein') then goto Sprachen;
   readmeja:
    clrscr;
    Writeln ('Der Text den der dicke Hund spricht ist in wei· und den Text den der kleine Hundspricht ist braun.');
    Writeln;
    Writeln ('In diesem Textadventur ist es ihr Ziel die Aufgaben die ihnen gestellt werden ');
    Writeln ('zu lîsen.');
    Writeln;
    klein;
    Writeln ('Do you know what you need to play with us?');
    warten;
    writeln;
    dick;
    writeln ('What?');
    klein;
    warten;
    writeln;
    writeln ('You need : Benzium Pro 2000, 2 Terra Byte KitomÑh RAM, 4,987566 MB Grafikkarte ');
    writeln ('    mit spezieller 3D Textbeschlaunigung, 7,5,6386 MB Festplattenspeicher,');
    writeln ('    CD - ROM Laufwerk zum selber drehen 50 Zoll Laufwerk!');
    warten;
    writeln;
    dick;
    writeln ('Woah !!!!');
    warten;
    Writeln;
    Writeln;
    neutral;
   Sprachen:
    Writeln ('In welcher Sprache sollen sich ihre Hunde unterhalten ?');
    writeln;
    Write   ('Deutsch oder Englisch ');
    Readln (Sprache);
    writeln;
    if (Sprache) = ('Deutsch') then Writeln ('Diese Sprache ist in der Version noch nicht vorhanden.');
    if (Sprache) = ('Englisch') then goto Episoden;
    warten ;
   Episoden:
    clrscr;
    writeln ('Episode 1 : Sie mÅssen eine Dose bekommen. Sie sind der kleine Hund.');
    writeln ('Episode 2 : Sie wollen Suppe essen. Sie sind der kleine Hund.');
    writeln ('Episode 3 : Big Food. Sie sind der kleine Hund.');
    Writeln;
    writeln ('Ende !');
    writeln;
    Write ('Welche Episode wollen sie spielen ? 1, 2 oder E ');
    Readln (Episode);
    if (Episode) = ('1') then goto Episode1;
    if (Episode) = ('2') then goto Episode2;
    if (episode) = ('3') then goto Episode3;
    if (Episode) = ('E') then goto Ende;
    goto episoden;
   BEGIN
    Episode1:
     clrscr;
     Textcolor (cyan);
     Writeln ('Die Dose liegt in einem Supermarkt und du stehst vor der TÅr. ');
     Writeln;
     warten;
      Textcolor (15);
      Writeln ('We have to get inside !');
      warten ;
      writeln;
      Textcolor (6);
      Writeln ('But how ?');
      warten ;
      Writeln;
      Textcolor (3);
      Writeln ('GegenstÑnde : TÅr, dicker Hund, Heli, Schild am Supermarkt, Karussel, Pferd');
      Writeln;
      Writeln ('Was sie tun kînnen : 1. TÅr anschauen 2. Hund anschauen 3. Heli anschauen ');
      Writeln ('  4. TÅr îffnen 5. Heli benutzen 6. Hund Witz erzÑhlen 7. Pferd anschauen');
      Writeln ('  8. Karusell anschauen 9. Pferd benutzen 10. Karusell benutzen ');
      Writeln ('  11. Schild anschauen 12. Ort wechseln ');
      Writeln;
      Textcolor (6);
      Write ('Was wollen sie jetzt tun ? (bitte die Zahl eingeben) ');
      Readln (dose1);
      writeln;
      if dose1 = ('1') then goto tueranschau;
      if dose1 = ('2') then goto hundanschau;
      if dose1 = ('3') then goto helianschau;
      if dose1 = ('4') then goto tueroff;
      if dose1 = ('5') then goto Helibenutz1;
      if Dose1 = ('6') then goto hundwitz;
      if Dose1 = ('7') then goto Pferdanschau;
      if dose1 = ('8') then goto Karusellanschau;
      if dose1 = ('9') then goto Pferdbenutz;
      if dose1 = ('10') then goto karusellbenutz;
      if dose1 = ('11') then goto schildanschau;
      if dose1 = ('12') then goto Ortwechsel1;
      if dose1 = ('cheat') then goto episode1a;
      goto episode1;
       schildanschau:
        dick;
        writeln ('It says : Opening tomorrow !');
        writeln;
        warten;
        klein;
        writeln ('When it is tomorrow ?');
        writeln;
        warten;
        dick;
        writeln ('In twentyfour hours !');
        writeln;
        warten;
        klein;
        writeln ('Twenty-four hours !?!?!?!?!?!?');
        writeln;
        warten;
       Ortwechsel1:
        Writeln ('Wohin soll ich den gehen ?');
        warten ;
        goto episode1;
       Karusellanschau:
        Writeln ('Spielzeugkarussel !');
        warten ;
        goto episode1;
       Pferdbenutz:
        Writeln ('Ich ha·e Pferde !');
        warten ;
        goto episode1;
       karusellbenutz:
        Writeln ('Soll ich etwa grÅn werden !');
        warten ;
        goto episode1;
       Pferdanschau:
        Textcolor (6);
        Writeln ('Spielzeugpferd !');
        warten ;
        goto episode1;
       Helibenutz1:
        Textcolor (15);
        Writeln ('Let me do that ! Let me do that !');
        writeln;
        warten ;
        Textcolor (6);
        Writeln ('Grrrrr !');
        writeln;
        warten ;
        Textcolor (15);
        Writeln ('Wow !!');
        wuh;
        writeln;
        warten ;
        Textcolor (6);
        Writeln ('Ihhhg !!');
        writeln;
        warten ;
        Textcolor (15);
        Writeln ('Yeah !');
        writeln;
        warten ;
        textcolor (6);
        goto episode1a;
       Hundwitz:
        Writeln ('Do you know what ?');
        writeln;
        Textcolor (15);
        warten ;
        Writeln ('What ?');
        writeln;
        warten ;
        Textcolor (6);
        Writeln ('Chickenbutt !');
        writeln;
        warten ;
        Textcolor (15);
        writeln ('Ha ! Ha ! Ha ! Ha ! Ha ! Ha ! Ha !');
        warten;
        goto episode1;
       Tueroff:
        Writeln ('Das geht nicht die funktioniert elektrisch !');
        warten ;
        goto episode1;
       Tueranschau:
        writeln ('Das is` ne elektrische !');
        warten ;
        goto episode1;
       Hundanschau:
        Writeln ('Das ist mein Freund, der dicke Hund (der mit dem wei·em Text) !');
        warten ;
        goto episode1;
       helianschau:
        writeln ('Spielzeughelikopter !');
        warten ;
        goto episode1;
   episode1a:
    clrscr;
    neutral;
    Writeln ('Du wachst gerade erst auf. Der dicke Hund sitzt wie blîd auf diesem Helikopter !');
    warten;
    Writeln;
    dick;
    Writeln ('Didn`t work ?');
    warten ;
    writeln;
    klein;
    Writeln ('You need some money ! ');
    warten;
    Writeln;
    dick;
    Writeln ('Give me some !');
    warten;
    writeln;
    klein;
    writeln ('I have nothing ! I am a dog !');
    writeln;
    warten;
    neutral;
    Writeln ('GegenstÑnde : TÅr, dicker Hund, Heli, Pferd, Karussel, Schild');
    writeln;
    Writeln ('Was sie kînnen : 1. Mit dem dickem Hund reden 2.Ortwechseln');
    writeln;
    klein;
    write ('Was tun kînnen (Is that cute !) : ');
    readln (dose2);
    if dose2 = ('1') then goto reden;
    if dose2 = ('2') then goto ortwechsel2;
    if dose2 = ('cheat') then goto reden;
    goto episode1a;
     Ortwechsel2:
      klein;
      writeln;
      Writeln ('Nicht ohne meinen Freund !');
      writeln;
      warten;
      goto episode1a;
     Reden:
      clrscr;
      neutral;
      writeln ('Was wollen sie sagen : 1. Ihn anschreien 2. Freundlich sein');
      writeln;
      Write ('Was wollen sie tun (Bitte Zahl eingeben) : ');
      readln (Dose3);
      writeln;
      if dose3 = ('1') then goto anschrei;
      if dose3 = ('2') then goto freundlich;
      if dose3 = ('cheat') then goto episode1b;
      goto reden;
      anschrei:
       klein;
       writeln ('Stupid dog !');
       writeln;
       warten;
       dick;
       writeln ('Why ?');
       writeln;
       warten;
       klein;
       writeln ('Grrrrrr !');
       writeln;
       warten;
       dick;
       writeln ('HÑÑ ? ');
       writeln;
       warten;
       neutral;
       Writeln ('Kleiner Hund ist kurz vor dem Angriff !');
       warten;
       writeln;
       Writeln ('Da kommt er ! Der "Thats wrong" - Typ.');
       warten;
       Wrong;
       writeln;
       writeln ('Is that cute ? ');
       warten;
       writeln;
       writeln ('But it`s wrong !!');
       mob;
       warten;
       goto episode1b;
      freundlich:
       klein;
       Writeln ('I need some help to get your can back .');
       warten;
       writeln;
       dick;
       writeln ('Which can ?');
       warten;
       writeln;
       klein;
       writeln ('Your can ! You lost it in the supermarket !');
       warten;
       dick;
       writeln;
       writeln ('No, I didn`t.');
       warten;
       klein;
       writeln;
       writeln ('Yes you did !');
       warten;
       dick;
       writeln;
       writeln ('No, I didn`t !!');
       warten;
       writeln;
       klein;
       writeln ('Yes you did !!!');
       warten;
       writeln;
       dick;
       writeln ('No, I didn`t !!!! Wow !!');
       wuh;
       warten;
       klein;
       writeln;
       writeln ('Ihhhg !!');;
       warten;
       goto reden;
    Episode1b:
     clrscr;
     neutral;
     Writeln ('Der Thats wrong - Typ steht zwischen dir und dem Supermarkt.');
     wrong;
     writeln;
     writeln ('What are you doing here ?');
     warten;
     writeln;
     klein;
     writeln ('We want to get his can back. It`s in the supermarket.');
     warten;
     writeln;
     writeln ('can you help us ?');
     warten;
     wrong;
     writeln;
     writeln ('Why should I do that ?');
     warten;
     writeln;
     neutral;
     writeln ('GegenstÑnde : Dicker Hund, Thats wrong - Typ, Supermarkt, Vogel');
     writeln;
     writeln ('Was sie tun kînnen : 1. Thats wrong - Type anschauen 2. Zum Supermarkt gehen');
     writeln ('  3. Dicken Hund um Rat fragen 4. Mit dem thats wrong - Typ reden ');
     writeln ('  5. Den Vogel anschauen');
     writeln;
     klein;
     write ('Was wollen sie tun ? : ');
     readln (Dose4);
     writeln;
     if dose4 = ('1') then goto wronganschau;
     if dose4 = ('2') then goto supermarktgehen;
     if dose4 = ('3') then goto ratfrag;
     if dose4 = ('4') then goto wrongreden;
     if dose4 = ('5') then goto vogelanschau;
     if dose4 = ('cheat') then goto wrongreden;
     goto episode1b;
     wronganschau:
      klein;
      writeln ('Das ist der Thats wrong - Typ.');
      warten;
      writeln ('Er ha·t Vîgel !');
      warten;
      goto episode1b;
     supermarktgehen:
      klein;
      writeln ('Der Thats wrong - Type steht mir im Weg .');
      warten;
      goto episode1b;
    ratfrag:
     klein;
     writeln ('Help me big dog .');
     warten;
     writeln;
     writeln ('Please !!');
     warten;
     writeln;
     dick;
     writeln ('I don`t know how !');
     warten;
     klein;
     Writeln;
     writeln ('You are really stupid !');
     warten;
     goto episode1b;
    vogelanschau:
     klein;
     writeln ('Man sind das blîde Tiere !');
     writeln;
     warten;
    wrongreden:
     clrscr;
     neutral;
     writeln ('Was wollen sie versuchen : 1 Ihm helfen 2. Ihn anschreien ');
     writeln ('  3. Dich einschleimen ');
     writeln;
     klein;
     write ('Was wollen sie nun sagen : ');
     readln (Dose5);
     writeln;
     if dose5 = ('1') then goto wrongbefrei;
     if dose5 = ('2') then goto wronganschrei;
     if dose5 = ('3') then goto wrongschleim;
     writeln;
     goto wrongreden;
     wronganschrei:
      klein;
      writeln ('You stupid person !');
      warten;
      writeln;
      writeln ('I hoped you will die here now !');
      warten;
      writeln;
      dick;
      writeln ('Me too ?');
      warten;
      writeln;
      writeln ('HÑÑ ?');
      warten;
      wrong;
      writeln;
      writeln ('Wrong !!!!!!!!');
      mob;
      warten;
      goto wrongreden;
     wrongschleim:
      klein;
      writeln ('Come on buddy.');
      writeln;
      warten;
      writeln;
      writeln ('We need some help. We need you.');
      warten;
      writeln;
      dick;
      writeln ('Yeah ! We need you. ');
      writeln;
      warten;
      writeln ('But why?');
      warten;
      wrong;
      writeln;
      writeln ('I hate people like you. You are so friendly and ahh !!');
      warten;
      goto wrongreden;
      warten;
     wrongbefrei:
      klein;
      writeln ('I can help you. ');
      warten;
      writeln;
      wrong;
      writeln ('Is that cute but how ?');
      warten;
      writeln;
      klein;
      writeln ('I can attack this stupid birds !');
      writeln;
      warten;
      wrong;
      writeln ('Please !! Do that and I will help you.');
      warten;
      anders;
      writeln;
      writeln ('Schirb ! Schirb ! Schirb ! Schirb !');
      writeln;
      warten;
      dick;
      writeln ('Wow !!');
      wuh;
      warten;
      writeln;
      anders;
      writeln ('Ihhg ! Ihhg ! ihhg ! Ihhg !');
      writeln;
      warten;
      wrong;
      writeln ('Thank`s I will go in and get your can !');
      writeln;
      warten;
      writeln ('Here, your can !');
      writeln;
      neutral;
      writeln ('Der Thats wrong - Type hat dem kleinen Hund die Dose in den Mund gesteckt. Nun geht er.');
      writeln;
      warten;
      klein;
      writeln ('Ihavegotyourcanback !');
      warten;
      writeln;
      dick;
      writeln ('I can`t understand you with that can in your mouth.');
      writeln;
      warten;
      neutral;
      writeln ('Der kleine Hund wÅrgt die Dose hervor und stellt sie vor den dicken Hund.');
      warten;
      writeln;
      dick;
      writeln ('What kind of can is that ? ');
      writeln;
      warten;
      writeln ('Mmmmm ... Nice can. I once had a can similar to this one. Yeah !!!');
      warten;
      goto episoden;
   END;
   Begin
    Episode2:
     clrscr;
     neutral;
     writeln ('Sie stehen auf dem Dach eines Hauses. Vor ihnen ist eine riesige SuppenschÅssel.');
     klein;
     writeln ('Today I wanne have soup !');
     warten;
     writeln;
     dick;
     writeln ('Yeah !!! Soup !!');
     warten;
     writeln;
     neutral;
     writeln ('GegenstÑnde : GelÑnder, Hund, SuppenschÅssel');
     writeln;
     writeln ('Was sie tun kînnen : 1. GelÑnder anschauen 2. Hund anschauen ');
     writeln ('    3. SuppenschÅssel anschauen 4. Zur SuppenschÅssel gehen ');
     writeln ('    5. Das GelÑnder benutzen um zur SuppenschÅssel zu kommen 6. Hund reden');
     writeln ('    7. Hund Witz erzÑhlen');
     writeln;
     klein;
     write ('Was wollen sie tun ? ');
     readln (Suppe1);
     writeln;
     if Suppe1 = ('1') then goto Gelanderanschau;
     if suppe1 = ('2') then goto Hundanschau2;
     if suppe1 = ('3') then goto Suppeanschau;
     if suppe1 = ('4') then goto Suppengehen;
     if suppe1 = ('5') then goto Gelandersuppe;
     if suppe1 = ('6') then goto Hundreden2;
     if suppe1 = ('7') then goto Hundewitz2;
     if suppe1 = ('cheat') then goto Episode2a;
     goto Episode2;
      Gelanderanschau:
       klein;
       writeln ('Ein GelÑnder. Toll nich.');
       writeln;
       warten;
       writeln ('Was fÅr`n toller Auftrag. Echt klasse.');
       warten;
       goto episode2;
     Hundanschau2:
      klein;
      writeln ('Das is mein Freund. Immer noch.');
      warten;
      goto episode2;
    Suppeanschau:
     klein;
     writeln ('Eine riesengro·e SuppenschÅssel !');
     warten;
     writeln;
     writeln ('Leider ist sie zu weit von mir entfernt.');
     warten;
     goto episode2;
    Suppengehen:
     klein;
     writeln ('O.K. bin unterwegs !');
     warten;
     writeln;
     writeln ('Ahhhhhhhhh !!!');
     sound (900);
     delay (7000);
     nosound;
     warten;
     writeln;
     neutral;
     writeln ('Der kleine Hund kommt gerade wieder nach oben.');
     warten;
     writeln;
     klein;
     writeln ('Da war ne`LÅcke auf dem Dach. Du .. Du .. ');
     warten;
     writeln;
     dick;
     writeln ('Ha ! Ha ! Ha ! Ha ! Ha ! Ha !');
     warten;
     goto Episode2;
    Gelandersuppe:
     neutral;
     writeln ('Der kleine Hund steigt auf das GelÑnder.');
     warten;
     writeln;
     klein;
     writeln ('Das reicht immer noch nicht. Ich komm einfach nicht rÅber. ');
     warten;
     writeln;
     writeln ('Ich komm jetzt zurÅck. ');
     warten;
     writeln;
     writeln ('Ahhhhhhhhhh !!!');
     sound (900);
     delay (7000);
     nosound;
     warten;
     writeln;
     neutral;
     writeln ('Er kommt wieder nach oben !');
     warten;
     writeln;
     klein;
     writeln ('That`s enough !! Get him !!');
     warten;
     writeln;
     dick;
     writeln ('Come on little dog ! You had to stop your hate.');
     warten;
     writeln;
     klein;
     writeln ('Grrr !!');
     writeln;
     warten;
     neutral;
     writeln ('Der kleine Hund beendet den Angriff, da der dicke Hund sein Freund ist');
     writeln;
     warten;
     writeln ('und besonder stÑrker und grî·er. Nicht zu vergessen, da· er die Geheimwaffe');
     warten;
     writeln;
     writeln ('den Wow - Angriff beherscht !');
     warten;
     goto Episode2;
    Hundewitz2:
     klein;
     writeln ('Two oranges walked over a street.');
     writeln;
     warten;
     writeln ('One stoped.');
     writeln;
     warten;
     writeln ('Why ?');
     warten;
     dick;
     writeln;
     writeln ('I don`t know. Why ?');
     warten;
     writeln;
     klein;
     writeln ('Because it rain out of juice !');
     warten;
     writeln;
     dick;
     writeln ('Hmmm !');
     warten;
     goto episode2;
    Hundreden2:
     klein;
     writeln ('Give me a boost !!');
     writeln;
     warten;
     dick;
     writeln ('O.K. !');
     warten;
     writeln;
     neutral;
     writeln ('Der kleine Hund fÑllt fast !');
     warten;
     writeln;
     klein;
     writeln ('Stop ! Stop !');
     warten;
     writeln;
     neutral;
     writeln ('Roms, ruschel, peng !');
     warten;
     writeln;
     klein;
     writeln ('Ahhhhh !');
     ahh;
     warten;
     goto episode2a;
   Episode2a:
    clrscr;
    neutral;
    writeln ('Der klein Hund ist auf die SuppenschÅssel geflogen.');
    warten;
    writeln;
    dick;
    writeln ('Are you O.K.?');
    warten;
    writeln;
    klein;
    writeln ('Yes, I have broken my leg.');
    warten;
    writeln;
    neutral;
    writeln ('GegenstÑnde : Knochen, Volgel, Boden, Hund');
    writeln;
    writeln ('Was sie tun kînnen : 1. Knochen anschauen 2. Vogel anschauen 3. Boden anschauen');
    writeln ('    4. Knochen nemmen 5. Vogel nemmen 6. Hund reden 7. Hund Witz erzÑhlen');
    writeln ('    8. Durch die Gegend humpeln 9. Vogel reden 10. Knochen zum Hund werfen');
    writeln ('    11. Vogel zum Hund werfen ');
    writeln;
    klein;
    write ('Was wollen sie tun ? ');
    readln (Suppe2);
    writeln;
    if suppe2 = ('1') then goto Knochenanschau;
    if suppe2 = ('2') then goto Vogelanschau2;
    if suppe2 = ('3') then goto Bodenanschau;
    if suppe2 = ('4') then goto Knochennem;
    if suppe2 = ('5') then goto vogelnem;
    if suppe2 = ('6') then goto Hundreden3;
    if suppe2 = ('7') then goto Hundwitz3;
    if suppe2 = ('8') then goto Humpeln;
    if suppe2 = ('9') then goto Vogelreden;
    if suppe2 = ('10') then goto Knochenwerf;
    if suppe2 = ('11') then goto Vogelwerf;
    if suppe2 = ('cheat') then goto Episode2b;
    warten;
    goto Episode2a;
    Knochenanschau:
     klein;
     writeln ('Tollen ein Knochen!');
     warten;
     writeln;
     writeln ('Hmm. Der past gut in meine Suppe.');
     warten;
     goto episode2a;
    Vogelanschau2:
     klein;
     writeln ('Ein toter Vogel.');
     warten;
     writeln;
     Writeln ('Ein toter Vogel in meiner Suppe ! Wiederlich !');
     warten;
     goto episode2a;
    Bodenanschau:
     klein;
     writeln ('Der Boden ist ganz trocken.');
     warten;
     writeln;
     writeln ('Das ist schlecht fÅr die Suppe wenn es nicht regnet !');
     warten;
     goto episode2a;
    Knochennem:
     klein;
     writeln ('Der bleibt hier liegen, fÅr meine Suppe. ');
     warten;
     goto Episode2a;
    vogelnem:
     klein;
     writeln ('Ich fass` doch keine toten Vîgel an!');
     warten;
     writeln;
     writeln ('Ich glaub der hat sie nich` mehr alle!');
     warten;
     writeln;
     dick;
     writeln ('Could be?');
     writeln;
     warten;
     goto episode2a;
    Hundreden3:
     dick;
     writeln ('How is it ?');
     warten;
     writeln;
     klein;
     writeln ('A little bit dry ?');
     warten;
     writeln;
     goto episode2a;
    Hundwitz3:
     klein;
     writeln ('Two oranges walked over a street.');
     writeln;
     warten;
     writeln ('One stoped.');
     writeln;
     warten;
     writeln ('Why ?');
     warten;
     dick;
     writeln;
     writeln ('I don`t know. Why ?');
     warten;
     writeln;
     klein;
     writeln ('Because it rain out of juice !');
     warten;
     writeln;
     dick;
     writeln ('Ha!');
     warten;
     goto episode2a;
    Humpeln:
     klein;
     writeln ('Wo soll ich denn hin humpeln!');
     warten;
     writeln;
     writeln ('Vieleicht soll ich mir ja auch noch das ander Bein brechen!');
     warten;
     goto episode2a;
    Vogelreden:
     klein;
     writeln ('Hey dead bird!');
     warten;
     writeln;
     dick;
     writeln ('Schirb! Schrib!');
     warten;
     writeln;
     klein;
     writeln ('Stop it you idiot!');
     warten;
     writeln;
     writeln ('You are a dog, not a bird!');
     warten;
     goto episode2a;
    Knochenwerf:
     klein;
     writeln ('Sag mal raffst du das heute noch mal!');
     warten;
     writeln;
     writeln ('Der gehîrt in meine Suppe!');
     warten;
     goto episode2a;
    Vogelwerf:
     klein;
     writeln ('O.K.!');
     warten;
     writeln;
     neutral;
     writeln ('Werf!');
     warten;
     writeln;
     dick;
     writeln ('Schluck!');
     warten;
     writeln;
     klein;
     writeln ('Have you eaten it ?');
     warten;
     writeln;
     dick;
     writeln ('Yes!');
     warten;
     writeln;
     klein;
     writeln ('Give it back!! ');
     warten;
     writeln;
     dick;
     writeln ('O.K.!');
     warten;
     writeln;
     dick;
     writeln ('Spuck!');
     warten;
     writeln;
     klein;
     writeln ('Everything green and wet! Do that again !');
     warten;
     writeln;
     dick;
     writeln ('O.K.! Spuck!');
     warten;
     writeln;
     klein;
     writeln ('Keep on going!');
     warten;
     goto episode2b;
    Episode2b:
     clrscr;
   END;
  episode3:
   Begin
   clrscr;
   neutral;
   Writeln ('Ihr befindet euch in der Stadt und euch ist langweilig und ihr habt');
   writeln ('Hunger.');
   writeln;
   dick;
   writeln ('We need foooot !!!!!');
   warten;
   writeln;
   klein;
   writeln ('Youre right, but where ist food, its sunday');
   warten;
   writeln;
   neutral;
   writeln ('In der nÑhe seht ihr ein Schild, eine Zeitung und eine Bank.');
   warten;
   Writeln ('Was wollt ihr machen? ');
   writeln ('1. Zeitung lesen, 2. Schild lesen, 3. auf Bank setzen');
   readln (Wahl1);
   if (Wahl1) = ('1') then goto Zeitung;
   if (Wahl1) = ('2') then goto Schild;
   if (Wahl1) = ('3') then goto Bank;
   if Wahl1 = ('cheat') then goto Wald;
   goto episode2;
   Zeitung:
    clrscr;
    neutral;
    writeln ('Ihr seht euch die Zeitung an.');
    warten;
    writeln;
    klein;
    Writeln ('Look there they want to have "BIG FOOT"!!!!');
    warten;
    writeln;
    dick;
    writeln ('I want Big foot too! ');
    warten;
    writeln;
    klein;
    writeln ('O.k. lets go !');
    warten;
    writeln;
    neutral;
    writeln ('Ihr macht euch auf den Weg zur Natur');
    goto Wald;
   Schild:
    clrscr;
    dick;
    writeln ('You must read this! ');
    warten;
    writeln;
    klein;
    writeln ('Shortcut this way, ohh yea i found the shortcut');
    warten;
    writeln;
    dick;
    writeln ('But we dont need the shortcut ');
    warten;
    writeln;
    klein;
    writeln ('Your right ');
    readln;
    goto episode2;
   Bank:
    clrscr;
    klein;
    writeln ('I will take a seat on this bank !');
    warten;
    writeln;
    dick;
    writeln ('I want sit too');
    warten;
    writeln;
    neutral;
    writeln ('Ihr nehmt Platz, geniest die frische Luft und Aussicht');
    warten;
    writeln;
    dick;
    writeln ('But I`m still hungry! ');
    warten;
    writeln;
    klein;
    writeln ('Me too, lets find some foot');
    warten;
    writeln;
    dick;
    writeln ('But where can we find Food and its still sunday ');
    warten;
    writeln;
    readln;
    goto episode2;
  Wald:
   clrscr;
   neutral;
   Writeln ('Ihr seid im Wald, die BÑume rascheln, die Vîgel vîgeln und es richt');
   writeln ('nach FrÅhling. Aber dafÅr habt ihr gar keinen Sinn, ihr habt hunger.');
   warten;
   writeln;
   klein;
   writeln ('Thats nature, no cars, no cats, no shoes and no Ñhh i dont know');
   warten;
   writeln ;
   dick;
   Writeln ('But here is no food too! ');
   warten;
   writeln;
   klein;
   Writeln ('But here are trees, fresh air and nice flowers');
   warten;
   writeln;
   dick;
   Writeln ('Ohh, trees !');
   warten;
   writeln;
   neutral;
   Writeln ('Was wollt ihr machen?');
   writeln ('1. Baum gie·en, 2. Pilz essen, 3. euch unterhalten, 4. Witz rei·en,');
   writeln ('5. Baum ansehen, 6. Pilz ansehen');
   readln(Wahl2);
   if (Wahl2) = ('1') then goto Baum;
   if (Wahl2) = ('2') then goto Pilzess;
   if (Wahl2) = ('3') then goto unterhalt;
   if (Wahl2) = ('4') then goto Witz;
   if (Wahl2) = ('5') then goto Baumseh;
   if (Wahl2) = ('6') then goto Pilzseh;
   if wahl2 = ('cheat') then goto north;
   goto Wald;
    Baum:
    clrscr;
    neutral;
    Writeln ('Der dicke Hund geht zu einem der BÑume, sieht ihn sich an, geht eine');
    writeln ('Runde um den Baum und hebt sein Bein.');
    warten;
    writeln;
    dick;
    writeln ('ahh, much better');
    warten;
    writeln;
    klein;
    writeln ('Let it be, it is oure home');
    warten;
    writeln;
    dick;
    Writeln ('whats up my friend, grr');
    warten;
    writeln;
    klein;
    writeln ('Its O.k. make the trees dirty make oure home dirty, its not my broblem');
    warten;
    writeln;
    neutral;
    Writeln ('Der dicke Hund sieht ein das dies ihr zuhause ist welches er beschmutzt');
    writeln ('Er geht weg vom Baum und setzt sich hin. Sein Magen knurrt.');
    readln;
    goto Wald;
   Pilzess:
    clrscr;
    neutral;
    Writeln ('Der dicke Hund geht zu einem der Pilze und i·t ihn, in der Hoffnung er schmeckt');
    writeln ('Der dicke wird auf einmal ganz grÅn.');
    warten;
    writeln;
    klein;
    Writeln ('Whats the matter?');
    warten;
    writeln;
    dick;
    Writeln ('I am in big hole, i am falling down');
    warten;
    writeln;
    klein;
    writeln ('I will help you');
    warten;
    writeln;
    dick;
    Writeln ('Wait I got a vision of the BIG FOOT');
    warten;
    warten;
    writeln;
    neutral;
    Writeln ('Der dicke Hund hatte eine Vision vom Big Food.');
    writeln ('Er regte sich hin und her. Nach einiger Zeit kam er zu sich.');
    writeln ('Er sah sich um, setzte sich hin und begann dem kleinem Hund');
    writeln ('den Weg zu beschreiben.');
    warten;
    writeln;
    dick;
    writeln ('We have to go to the northside of this forest. ');
    warten;
    writeln;
    klein;
    Writeln ('Are you sure ?');
    warten;
    writeln;
    dick;
    Writeln (' Nope !');
    warten;
    writeln;
    klein;
    writeln ('O.k. lets go !');
    readln;
    goto North;
   unterhalt:
    clrscr;
    klein;
    writeln ('What do you feel ?');
    warten;
    Writeln;
    dick;
    Writeln ('Pain !');
    warten;
    writeln;
    klein;
    writeln ('Why ?');
    warten;
    writeln;
    dick;
    writeln ('Because I`m hungry !');
    warten;
    writeln;
    klein;
    Writeln ('Why ? ');
    warten;
    writeln;
    dick;
    writeln ('Forget it ');
    warten;
    writeln;
    klein;
    writeln ('Why ?');
    warten;
    writeln;
    dick;
    writeln ('GRRRRRRRRRRRR, thats why !!!!');
    readln;
    goto Wald;
   Witz:
    clrscr;
    klein;
    writeln ('Whats black and orange ?');
    warten;
    writeln;
    dick;
    writeln ('I dont know ');
    warten;
    writeln;
    klein;
    writeln ('A stunk with orangecake, hahahahahahahah, hahahah !!!!! ');
    warten;
    writeln;
    dick;
    writeln ('HOHOHHOHO !');
    warten;
    writeln;
    neutral;
    writeln ('Da kommt ein Stinktier mit Orangenkuchen vorbei und fragt:" Whats so funny?"');
    readln;
    goto Wald;
   Baumseh:
    clrscr;
    dick;
    writeln ('It is a part of oure home !');
    readln;
    goto Wald;
   Pilzseh:
    Clrscr;
    dick;
    writeln ('He is red and have got bretty wight points on it');
    warten;
    writeln;
    klein;
    writeln ('He looks like poison! ');
    warten;
    writeln;
    dick;
    writeln ('No he isn`t poison he is funny, but he smell`s bad');
    readln;
    goto Wald;
  North:
   clrscr;
   neutral;
   writeln ('Ihr steht plîtzlich vor einem gro·en Haus, da· aussieht wie ein');
   writeln ('Fast foodladen.');
   writeln ('Ihr seht: ein Schild, eine TÅr, eine Leiter, einen Kartong und ein');
   writeln ('Loch im Boden.');
   Writeln ('Was wollt ihr machen? 1.Schild ansehen, 2.TÅr ansehen, 3.TÅr îffnen,');
   writeln ('4. Zur TÅr hineinsehen, 5. Leiter ansehen, 6. Leiter benutzen,');
   writeln ('7. Kartong ansehen, 8. Kartong îffnen, 9. Loch ansehen');
   readln (Wahl3);
   if (Wahl3) = ('1') then goto Schildles;
   if (Wahl3) = ('2') then goto Tuerguck;
   if (Wahl3) = ('3') then goto Tuerdrueck;
   if (Wahl3) = ('4') then goto Reinguck;
   if (Wahl3) = ('5') then goto Leiterguck;
   if (Wahl3) = ('6') then goto Leiternutz;
   if (Wahl3) = ('7') then goto Kartongguck;
   if (Wahl3) = ('8') then goto Kartongoe;
   if (Wahl3) = ('9') then goto Loch;
   {if wahl3 = ('cheat') then goto ;}
   goto North;
    Schildles:
     clrscr;
     neutral;
     writeln ('Der Dicke Hund geht zum Schild und versucht zu lesen');
     warten;
     writeln;
     dick;
     Writeln ('Better you read the text! ');
     warten;
     writeln;
     klein;
     writeln ('Opening tmorrow! When is tomorrow? ');
     warten;
     writeln;
     dick;
     Writeln ('In twenty-four hours ');
     warten;
     writeln;
     klein;
     Writeln ('In twenty-four hours, what can we do? ');
     warten;
     writeln;
     dick;
     writeln ('Lets break in');
     readln;
     goto North;
   Tuerguck:
    clrscr;
    dick;
    writeln ('Thats an eletro door');
    warten;
    writeln;
    klein;
    Writeln ('Oh I hate this doors.');
    readln;
    goto North;
   Tuerdrueck:
    clrscr;
    neutral;
    writeln ('Der dicke versucht die TÅr zu rammen.');
    warten;
    writeln;
    dick;
    writeln ('Out of my way !!!!!!');
    warten;
    writeln;
    neutral;
    writeln ('Doch er holte sich nur eine gro·e Beule am Kopf');
    warten;
    writeln;
    klein;
    writeln ('We must find an another way to get inside.');
    readln;
    goto North;
   Reinguck:
    clrscr;
    neutral;
    writeln ('Im Raum steht eine Theke auf der Leckere Sachen liegen');
    warten;
    writeln;
    dick;
    writeln ('Ohhhhhhhh');
    warten;
    writeln;
    klein;
    writeln ('Ahhhhhhhhhh');
    readln;
    goto North;
   Leiterguck:
    clrscr;
    dick;
    writeln ('A Chance to come into the Atic');
    readln;
    goto North;
   Leiternutz:
    clrscr;
    neutral;
    Writeln ('Die beiden gehen mit MÅhe die Leiter hoch und erreichen den Dachboden');
    readln;
    goto Dach;
   Kartongguck:
    clrscr;
    dick;
    Writeln ('Looks like food !');
    warten;
    writeln;
    klein;
    writeln ('Oh yeah, food, food, i like food');
    readln;
    goto North;
   Kartongoe:
    clrscr;
    klein;
    writeln ('Open it! ');
    warten;
    writeln;
    dick;
    writeln ('O.k. ');
    warten;
    writeln;
    klein;
    writeln ('What is in the box ?');
    warten;
    writeln;
    dick;
    writeln ('Nothing');
    readln;
    goto North;
   Loch:
    clrscr;
    neutral;
    writeln ('Das Loch ist nicht sehr tief.');
    warten;
    writeln;
    dick;
    writeln ('I cant see nothing in it.');
    warten;
    writeln;
    klein;
    writeln ('Maybe the hole is for a bone');
    readln;
    goto North;
   Dach:
 end;
 Ende:
 warten;
END.